/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg21550867_componentesgraficos_u3_jmd;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class Alumnos extends javax.swing.JFrame {

    String sPaisAlumno, sEstadoAlumno, sCalleAlumno, sColoniaAlumno, sNumeroAlumno, sNombreAlumno;
    String sHardware = "", sSoftware = "", sArquitecura = "", sSeguridad = "", sDisenioWeb = "", sProgramacionWeb = "", sDesarrolloGra = "", sAplicacionesHibridas = "", sProgramacionMov = "", sRedes = "", sSoporte = "", sElectronicaComp = "";

    /**
     * Creates new form NewJFrame
     */
    public Alumnos() {
        initComponents();
        String[] arrayPaises = new String[]{"Selecciona Pais", "Mexico", "Estados Unidos", "Canada", "Colombia"};
        cbxPais.setModel(new DefaultComboBoxModel(arrayPaises));

        /*
        for (int i = 0; i < arrayPaises.length; i++) {
            cbxPais.addItem(arrayPaises[i]);
        }
         */
        lblEstado.setVisible(false);
        cbxEstado.setVisible(false);

        lblCalle.setVisible(false);
        txtCalle.setVisible(false);
        lblColonia.setVisible(false);
        txtColonia.setVisible(false);
        lblNumero.setVisible(false);
        txtNumero.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxPais = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        rbnDireccion = new javax.swing.JRadioButton();
        lblCalle = new javax.swing.JLabel();
        txtCalle = new javax.swing.JTextField();
        lblNumero = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblColonia = new javax.swing.JLabel();
        txtColonia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chxAplicacionesHibridas = new javax.swing.JCheckBox();
        chxHardware = new javax.swing.JCheckBox();
        chxSoftware = new javax.swing.JCheckBox();
        chxArquitecturaDeComputadoras = new javax.swing.JCheckBox();
        chxProgramacionWeb = new javax.swing.JCheckBox();
        chxProgramacionMovil = new javax.swing.JCheckBox();
        chxDesarrolloGrafico = new javax.swing.JCheckBox();
        chxRedes = new javax.swing.JCheckBox();
        chxSeguridad = new javax.swing.JCheckBox();
        chxSoporteYMantenimiento = new javax.swing.JCheckBox();
        chxElectronicaComputacional = new javax.swing.JCheckBox();
        chxDisenioWeb = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Localidad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 330, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 610, 60, 20));

        cbxPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 280, -1));

        jLabel4.setText("Pais:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 280, -1));

        rbnDireccion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbnDireccion.setText("Con direccion");
        rbnDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(rbnDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        lblCalle.setText("Calle:");
        getContentPane().add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 270, -1));

        lblNumero.setText("Numero:");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 270, -1));

        lblColonia.setText("Colonia:");
        getContentPane().add(lblColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));
        getContentPane().add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 270, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Preferencias:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        chxAplicacionesHibridas.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxAplicacionesHibridas.setText("Aplicaciones Hibridas");
        chxAplicacionesHibridas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxAplicacionesHibridasActionPerformed(evt);
            }
        });
        getContentPane().add(chxAplicacionesHibridas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        chxHardware.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxHardware.setText("Hardware");
        chxHardware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxHardwareActionPerformed(evt);
            }
        });
        getContentPane().add(chxHardware, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        chxSoftware.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxSoftware.setText("Software");
        chxSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSoftwareActionPerformed(evt);
            }
        });
        getContentPane().add(chxSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 20));

        chxArquitecturaDeComputadoras.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxArquitecturaDeComputadoras.setText("Arquitectura de computadoras");
        chxArquitecturaDeComputadoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxArquitecturaDeComputadorasActionPerformed(evt);
            }
        });
        getContentPane().add(chxArquitecturaDeComputadoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        chxProgramacionWeb.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxProgramacionWeb.setText("Programacion web");
        chxProgramacionWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxProgramacionWebActionPerformed(evt);
            }
        });
        getContentPane().add(chxProgramacionWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        chxProgramacionMovil.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxProgramacionMovil.setText("Programacion movil");
        chxProgramacionMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxProgramacionMovilActionPerformed(evt);
            }
        });
        getContentPane().add(chxProgramacionMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, -1));

        chxDesarrolloGrafico.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxDesarrolloGrafico.setText("Desarrollo grafico");
        chxDesarrolloGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxDesarrolloGraficoActionPerformed(evt);
            }
        });
        getContentPane().add(chxDesarrolloGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        chxRedes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxRedes.setText("Redes");
        chxRedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxRedesActionPerformed(evt);
            }
        });
        getContentPane().add(chxRedes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        chxSeguridad.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxSeguridad.setText("Seguridad");
        chxSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSeguridadActionPerformed(evt);
            }
        });
        getContentPane().add(chxSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        chxSoporteYMantenimiento.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxSoporteYMantenimiento.setText("Soporte y mantenimiento");
        chxSoporteYMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxSoporteYMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(chxSoporteYMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, -1));

        chxElectronicaComputacional.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxElectronicaComputacional.setText("Electonica computacional");
        chxElectronicaComputacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxElectronicaComputacionalActionPerformed(evt);
            }
        });
        getContentPane().add(chxElectronicaComputacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        chxDisenioWeb.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        chxDisenioWeb.setText("Diseño web");
        chxDisenioWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chxDisenioWebActionPerformed(evt);
            }
        });
        getContentPane().add(chxDisenioWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnDireccionActionPerformed
        // TODO add your handling code here:
        if (rbnDireccion.isSelected()) {
            lblCalle.setVisible(true);
            txtCalle.setVisible(true);
            lblColonia.setVisible(true);
            txtColonia.setVisible(true);
            lblNumero.setVisible(true);
            txtNumero.setVisible(true);

        } else {
            lblCalle.setVisible(false);
            txtCalle.setVisible(false);
            lblColonia.setVisible(false);
            txtColonia.setVisible(false);
            lblNumero.setVisible(false);
            txtNumero.setVisible(false);
        }
    }//GEN-LAST:event_rbnDireccionActionPerformed

    private void chxHardwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxHardwareActionPerformed
        // TODO add your handling code here:
        if (chxHardware.isSelected()) {
            sHardware = "Hardware";
        } else {
            sHardware = "";
        }
    }//GEN-LAST:event_chxHardwareActionPerformed

    private void chxAplicacionesHibridasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxAplicacionesHibridasActionPerformed
        // TODO add your handling code here:
        if (chxAplicacionesHibridas.isSelected()) {
            sAplicacionesHibridas = "Aplicaciones Hibridas";
        } else {
            sAplicacionesHibridas = "";
        }
    }//GEN-LAST:event_chxAplicacionesHibridasActionPerformed

    private void chxSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSeguridadActionPerformed
        // TODO add your handling code here:
        if (chxSeguridad.isSelected()) {
            sSeguridad = "Seguridad";
        } else {
            sSeguridad = "";
        }
    }//GEN-LAST:event_chxSeguridadActionPerformed

    private void chxSoporteYMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSoporteYMantenimientoActionPerformed
        // TODO add your handling code here:
        if (chxSoporteYMantenimiento.isSelected()) {
            sSoporte = "Soporte y Mantenimiento";
        } else {
            sSoporte = "";
        }
    }//GEN-LAST:event_chxSoporteYMantenimientoActionPerformed

    private void chxElectronicaComputacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxElectronicaComputacionalActionPerformed
        // TODO add your handling code here:
        if (chxElectronicaComputacional.isSelected()) {
            sElectronicaComp = "Electronica Computacional";
        } else {
            sElectronicaComp = "";
        }
    }//GEN-LAST:event_chxElectronicaComputacionalActionPerformed

    private void chxDisenioWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxDisenioWebActionPerformed
        // TODO add your handling code here:
        if (chxDisenioWeb.isSelected()) {
            sDisenioWeb = "Diseño Web";
        } else {
            sDisenioWeb = "";
        }
    }//GEN-LAST:event_chxDisenioWebActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Obteniendo los nombres de los formularios, para guardar:
        sNombreAlumno = txtNombre.getText();
        System.out.println("Nombre: " + sNombreAlumno);
        System.out.println("Pais: " + sPaisAlumno);
        System.out.println("Estado: " + sEstadoAlumno);

        if (rbnDireccion.isSelected()) {
            sCalleAlumno = txtCalle.getText();
            sColoniaAlumno = txtColonia.getText();
            sNumeroAlumno = txtNumero.getText();
            System.out.println("Calle: " + sCalleAlumno);
            System.out.println("Colonia: " + sColoniaAlumno);
            System.out.println("Numero: " + sNumeroAlumno);
        }
        System.out.println("Preferencias: \n" + validarVacio(sHardware) + validarVacio(sArquitecura) + validarVacio(sAplicacionesHibridas)
                + validarVacio(sDesarrolloGra) + validarVacio(sDisenioWeb) + validarVacio(sElectronicaComp) + validarVacio(sProgramacionMov)
                + validarVacio(sProgramacionWeb) + validarVacio(sRedes) + validarVacio(sSeguridad) + validarVacio(sSoftware)
                + validarVacio(sSoporte));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void chxProgramacionWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxProgramacionWebActionPerformed
        // TODO add your handling code here:
        if (chxProgramacionWeb.isSelected()) {
            sProgramacionWeb = "Programacion Web";
        } else {
            sProgramacionWeb = "";
        }
    }//GEN-LAST:event_chxProgramacionWebActionPerformed

    private String validarVacio(String sVal) {
        if (sVal.equals("")) {
            return "";
        } else {
            return sVal + "\n";
        }
    }

    private void cbxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaisActionPerformed
        // TODO add your handling code here:

        String sPais = cbxPais.getSelectedItem().toString();
        String[] arrayEstados = null;
        switch (sPais) {
            case "Mexico" : {
                arrayEstados = new String[]{"Selecciona Estados", "Chihuahua", "Nuevo Leon", "Guadalajara", "Sonora", "Durango", "Zacatecas"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            }
            case "Estados Unidos" : {
                arrayEstados = new String[]{"Selecciona Estados", "Texas", "Washington DC", "Texas", "Nueva York", "California", "Nevada"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            }
            case "Canada" :{
                arrayEstados = new String[]{"Selecciona Estados", "Alberta", "Columbia Británica", "Manitoba", "Nueva Escocia", "Ontario", "Quebec"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            }
            case "Colombia" : {
                arrayEstados = new String[]{"Selecciona Estados", "Medellin", "Atlantico", "Bolivar", "Amazonas", "Meta", "Antioquia"};
                cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            }
            default : {
                JOptionPane.showMessageDialog(null, "Selecciona un pais para continuar.", "Error de seleccion.", JOptionPane.ERROR_MESSAGE);
                lblEstado.setVisible(false);
                cbxEstado.setVisible(false);
            }

        }
        if (!sPais.equals("Selecciona Pais")) {
            cbxEstado.setModel(new DefaultComboBoxModel(arrayEstados));
            lblEstado.setVisible(true);
            cbxEstado.setVisible(true);
            sPaisAlumno = sPais;
        }

    }//GEN-LAST:event_cbxPaisActionPerformed

    private void cbxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoActionPerformed
        // TODO add your handling code here:
        String sEstado = cbxEstado.getSelectedItem().toString();
        if (!sEstado.equals("Selecciona Pais")) {
            sEstadoAlumno = sEstado;
        }
    }//GEN-LAST:event_cbxEstadoActionPerformed

    private void chxProgramacionMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxProgramacionMovilActionPerformed
        // TODO add your handling code here:
        if (chxProgramacionMovil.isSelected()) {
            sProgramacionMov = "Programacion Movil";
        } else {
            sProgramacionMov = "";
        }
    }//GEN-LAST:event_chxProgramacionMovilActionPerformed

    private void chxDesarrolloGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxDesarrolloGraficoActionPerformed
        // TODO add your handling code here:
        if (chxDesarrolloGrafico.isSelected()) {
            sDesarrolloGra = "Desarrollo Grafico";
        } else {
            sDesarrolloGra = "";
        }
    }//GEN-LAST:event_chxDesarrolloGraficoActionPerformed

    private void chxRedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxRedesActionPerformed
        // TODO add your handling code here:
        if (chxRedes.isSelected()) {
            sRedes = "redes";
        } else {
            sRedes = "";
        }
    }//GEN-LAST:event_chxRedesActionPerformed

    private void chxArquitecturaDeComputadorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxArquitecturaDeComputadorasActionPerformed
        // TODO add your handling code here:
        if (chxArquitecturaDeComputadoras.isSelected()) {
            sArquitecura = "Arquitectura de computadoras";
        } else {
            sArquitecura = "";
        }
    }//GEN-LAST:event_chxArquitecturaDeComputadorasActionPerformed

    private void chxSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chxSoftwareActionPerformed
        // TODO add your handling code here:
        if (chxSoftware.isSelected()) {
            sSoftware = "Software";
        } else {
            sSoftware = "";
        }
    }//GEN-LAST:event_chxSoftwareActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxPais;
    private javax.swing.JCheckBox chxAplicacionesHibridas;
    private javax.swing.JCheckBox chxArquitecturaDeComputadoras;
    private javax.swing.JCheckBox chxDesarrolloGrafico;
    private javax.swing.JCheckBox chxDisenioWeb;
    private javax.swing.JCheckBox chxElectronicaComputacional;
    private javax.swing.JCheckBox chxHardware;
    private javax.swing.JCheckBox chxProgramacionMovil;
    private javax.swing.JCheckBox chxProgramacionWeb;
    private javax.swing.JCheckBox chxRedes;
    private javax.swing.JCheckBox chxSeguridad;
    private javax.swing.JCheckBox chxSoftware;
    private javax.swing.JCheckBox chxSoporteYMantenimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblColonia;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JRadioButton rbnDireccion;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
